apiVersion: v1
kind: Pod
metadata:
  name: kubia-full
  namespace: sentiment-namespace
  labels:
    name: kubia-full
    env: test
    type: data-process
spec:
  nodeSelector:
    gpu: "false"
  containers:
  - image: luksa/kubia
    name: kubia-container
    ports:
    - containerPort: 8080
      protocol: TCP